### ISSUE TITLE
Frontend Tasarımı

### ISSUE THREAD

**Issue by rasnesakam** [rasnesakam/Trascendence#13]
Uygulama için önyüz tasarımı gerek
@b-tekinli burayı daha renklendirirse iyi olur.
Yoruma oluşturulması gereken sayfaları yazabilir misin lütfen?

**Comment by b-tekinli** [comment]
Login Page

![login](https://github.com/rasnesakam/Trascendence/assets/64313175/05510263-6ba6-4b4e-8932-99b9286cafd6)

**Comment by b-tekinli** [comment]
Main Page
![Ana-Sayfa](https://github.com/rasnesakam/Trascendence/assets/64313175/b0f66214-c2f7-44ad-85bf-7ed195e99b35)

**Comment by b-tekinli** [comment]
Game Page
![Game page](https://github.com/rasnesakam/Trascendence/assets/64313175/f06d8c43-ead8-444f-b57e-6c33990cf39f)

**Comment by b-tekinli** [comment]
Score Page
![Score](https://github.com/rasnesakam/Trascendence/assets/64313175/58ae5a84-13df-4623-9f84-b8e4954a8f99)

**Comment by b-tekinli** [comment]
Match Page
![Match](https://github.com/rasnesakam/Trascendence/assets/64313175/94fe0386-9ced-4e87-bc7f-7aa922a09fc0)

**Comment by b-tekinli** [comment]
Loser and Winner Pages
![Losing](https://github.com/rasnesakam/Trascendence/assets/64313175/6f0ef0e5-c2e3-4e04-b607-6b31bd927e98)
![Winner](https://github.com/rasnesakam/Trascendence/assets/64313175/f0790e65-e962-4bd9-8419-2f163e898219)

**Comment by b-tekinli** [comment]
Tournament Page
![Tournament](https://github.com/rasnesakam/Trascendence/assets/64313175/566f159c-a71b-479c-b924-9fe6a08b0d62)

**Comment by b-tekinli** [comment]
Error 404 Page
![404](https://github.com/rasnesakam/Trascendence/assets/64313175/862b0a3b-95b5-46b1-b595-f223e52a8b41)
