### ISSUE TITLE
playCode

### ISSUE THREAD

**Issue by ayumusakdiken** [rasnesakam/Trascendence#153]
api/auth/sign-in/42 endpointine post gönderildikten sonra dönen responsun içerisine playCode eklenecek. playCode içerisinde bir şey barındırmıyorsa null değeri taşıyacak. Frontend kısmında playCode içerisinde bir değer barındırmıyorsa playCode istenecek. playCode'lar oyuna giriş yapabilmemizi sağlayacak

**Comment by rasnesakam** [comment]
- Veritabanına play_code ve has_play_code alanları eklendi (api_usermodel tablosuna).
- play_code bilgisini güncellemek için profil güncelleme endpointi yazıldı
