### ISSUE TITLE
Instabilities on Dockerfile

### ISSUE THREAD

**Issue by rasnesakam** [rasnesakam/Trascendence#186]
When we run `docker compose up`, the thing we expect is, the exposing port `80` or `443` for connection. But sometimes, port forwarding breaks and instead of `80`, port `8000` exposing.

Normally, we are exposing port `8000` for only frontend service. so, my asumption is that, when gateway service downs, frontend still runs and thats causing the problem. But we need more research. @b-tekinli, please provide me some log information such as:
* docker ps
* docker log for nginx and backend and websocket

**Comment by b-tekinli** [comment]
nginx kalkmıyordu tşk
