### ISSUE TITLE
Yetkilendirme işlemi

### ISSUE THREAD

**Issue by rasnesakam** [rasnesakam/Trascendence#35]
Beyza hocam hatırlarsan yetkilendirme işlemi için tüm şeyleri backendde yapalım demiştim. Ancak bir daha düşününce bunu frontendde yapmak daha sağlıklı olur sanırım. Giriş ekranında. 42 ile giriş butonu koyabilir miyiz? Bu buton 42 ile giriş için bir sayfaya yönlendirecek, ardından bir kod ile geri dönecek. Bu kod ile de access token ve refresh token alınıyordu hani.
Biz sunucuda sadece kullanıcı bilgilerini tutalım, token olarak da 42 nin verdiği tokeni kullanalım. Bunun hakkında daha detaylı konuşalım yarın.

**Comment by b-tekinli** [comment]
Hocam zaten giriş ekranında 42 ile giriş butonu var ve [intra](https://auth.42.fr/auth/realms/students-42/protocol/openid-connect/auth?client_id=intra&redirect_uri=https%3A%2F%2Fprofile.intra.42.fr%2Fusers%2Fauth%2Fkeycloak_student%2Fcallback&response_type=code&state=255991f730e5dfd6bf3f6fa98e483a0bfce39a23c17bf3cb) sayfasına yönlendiriyor. Yarın detaylıca konuşuruz.
