### ISSUE TITLE
Yapılacak Modüller

### ISSUE THREAD

**Issue by rasnesakam** [rasnesakam/Trascendence#42]
# Kararlaştırılmış olan yapılacak modüller listesi şu şekildedir:
- [x] Use framework (Django) as backend ( + 1 )
- [x] Use framework or toolkit (Bootstrap) as frontend ( + 0.5 )
- [x] Use database as backend ( + 0.5 )
- [x] Standard user management, authentication, users across tournaments ( + 1 )
- [x] Live chat ( + 1 )
- [x] Design backend as microservice ( + 1 )
- [x] Introduce an AI Opponent ( + 1 )
- [x] User and Game Stats Dashboards ( + 0.5 )
- [x] Game Customization Options. ( + 1 )
- [x] Support on all devices ( + 0.5 )
- [x] Server-Side Rendering (SSR) Integration. ( + 0.5 )

# Opsiyonel Modüller:
- [x] Implementing remote authentication ( + 1 )
- [x]  Expanding Browser Compatibility ( + 0.5 )
- [x] Responsive ( + 0.5 )
- [ ] Multiplayer support ( + 1 )
- [ ] Add Another Game with User History and Matchmaking. ( + 1 )
- [ ] Use of advanced 3D techniques ( + 1 )
- [ ] Implement two factor auth and jwt ( + 1 )
- [ ] Store the score of a tournament in the blockchain ( + 1 )
- [ ] Remote Players ( + 1 )
- [ ] Infrastructure setup for log management ( + 1 )

**Comment by rasnesakam** [comment]
BU KAPANMAYACAK!!!!

**Comment by b-tekinli** [comment]
KAPANACAAKK !!!1!!1!1!!!!bir!!!!!!
