### ISSUE TITLE
Connect backend with frontend

### ISSUE THREAD

**Issue by rasnesakam** [rasnesakam/Trascendence#60]
# Description
We need to connect backend with frontend, and made our application production-ready phase.
To do this, we may inspire this shcema below:

![Design Schema](https://github.com/rasnesakam/Trascendence/assets/45129228/5b87d217-8349-4b67-8e5d-1d01b3e3b838)

## NGINX
Nginx will be gateway for our application. It will take, secure and redirect the requests to our services.

## Backend Service
Backend service will handle logic codes for our application. For security reasons, backend and db services will host in private network. But backend will also be in the network that nginx can see it.

## Database
Database is responsible for holding our persisted entities.

## Frontend
Frontend is the representational layer for our project. Users will interact whole application through frontend service

## Notification Service
I am not sure if I need to put it but we need websockets for functionalities like status checking, messaging, and invitation control. For this, we can make new service to handle websocket operations

**Comment by hnur-eris** [comment]
hocam bacceknd/transendece içerisine bir tane daha ekleme yapmamız gerekiyor ASGI yı kullanacağımız için:
ASGI_APPLICATION = 'myproject.asgi.application' 
temel kalıp bu şekildeymiş
Bi saat içerisinde backend in de docker ını ASGI üzerinde bitirmeyi hedefliyorum bana şans dileyin...

**Comment by hnur-eris** [comment]
FROM python:3.12

WORKDIR /app

COPY . .

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


RUN python -m pip install daphne

COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE  8000
#ENTRYPOINT [ "python" ]
#CMD [ "app/manage.py", "runserver"]
CMD [ "daphne", "app.asgi:application", "-b", "0.0.0.0:8000"]


hocam ASGI kendi içersinde 3 e ayrılıyormuş biz burda zannımca daphne kullanmalıyız. bunun için gerekli komut argümanlarını çalıştırırken ikinci kısma ne koyduysam hata aldım sizce ne koymalıyım
