### ISSUE TITLE
New Endpoints

### ISSUE THREAD

**Issue by rasnesakam** [rasnesakam/Trascendence#80]
### Auth
- [ ] ~/api/auth/sign-in/42
- [ ] ~/api/auth/sign-in/
- [ ] ~/api/auth/sign-up/

### Interacts
- [ ] ~/api/interacts/friends
- [ ] ~/api/interacts/friends/add
- [ ] ~/api/interacts/friends/delete/{{username}}
- [ ] ~/api/interacts/invitations
- [ ] ~/api/interacts/invitations/accept/{{invitationCode}}
- [ ] ~/api/interacts/invitations/delete/{{invitationCode}}
- [ ] ~/api/interacts/blacklist
- [ ] ~/api/interacts/blacklist/add
- [ ] ~/api/interacts/blacklist/delete/{{username}}

### Tournaments
- [ ] ~/api/tournaments
- [ ] ~/api/tournaments/{{tournamentCode}}
- [ ] ~/api/tournaments/{{tournamentCode}}/matches
- [ ] ~/api/tournaments/{{tournamentCode}}/users/
- [ ] ~/api/tournaments/create
- [ ] ~/api/tournaments/{{tournamentCode}}/delete/{{username}}
- [ ] ~/api/tournaments/invitations
- [ ] ~/api/tournaments/invitations/accept/{{tournamentCode}}
- [ ] ~/api/tournaments/invitations/delete/{{tournamentCode}}

### Uploads
- [ ] ~/api/uploads/upload/
- [ ] ~/api/uploads/delete/{{file}}

### Profile
- [ ] ~/api/profile/{{username}}

**Comment by hnur-eris** [comment]
~/api/interacts/blacklist/delete/{{username}} 
hocam  interacts kısmındaki bu kısımda size sormadan değiştirmek istemedim

**Comment by hnur-eris** [comment]
path('tournaments/<tournamentcode>/<username>/delete', TorunamentsView.remove_tournament_user),
hocam burada fonksiyonun içerisinde username kullanılmamış o yüzden asıl kısma ekleyemedim
